MINT_CLIENT_MAP = {
    3:  "TEST CLIENT",
    4:  "Holiday Company",
    5:  "Brodie Cashmere Ltd",
    6:  "5411 Packaging",
    7:  "TT Studios",
    8:  "Rove",
    9:  "Shirty Group",
    10: "Deiji Studios",
    11: "LF Markey",
    12: "House of Sunny",
    13: "Kivari",
    14: "Theo The Label",
    15: "Pink City Prints",
    16: "Nude Lucy",
    17: "Huishan Zhang Flagship",
    18: "Emily Lovelock",
    19: "Acler",
    20: "Emilia Wickstead",
    21: "Staple & Hue",
    22: "Third Form",
    23: "Sancia",
    24: "Gingham Traders Pty Ltd dba Lorna Murray",
    25: "Lou Swim",
    26: "Ziah",
    27: "Maggie The Label",
    28: "Motel",
    29: "Pony Rider",
    30: "TEST2",
    31: "One Teaspoon",
}